site_name: k8s-certified

repo_name: 'benauca/my-kubernetes-notes'
repo_url: 'https://github.com/benauca/my-kubernetes-notes'
theme:
  name: material
  features:
  - navigation.tabs
  palette:
    primary: 'indigo'
    accent: 'red'
plugins:
  - search
extra_css: [extra.css]
nav:
  - Home: "index.md"
  - Architecture: "pages/architecture.md"
  - CKAD:
    - Getting Started: "pages/ckad/introduction.md"
    - Conceptos Básicos: "pages/ckad/basic-concepts.md"
    - Configuración: "pages/ckad/configuration.md"
    - Multi-Container: "pages/ckad/multi-container-pods.md"
    - Observabilicad: "pages/ckad/observabilty.md"
    - Pod Design: "pages/ckad/pod-design.md"
    - Servicios y Networking: "pages/ckad/services-networking.md"
    - Estado y Persistencia: "pages/ckad/state-persistence.md"
  - CKA:
    - Aspectos Básicos: "pages/TerraformBasics.md"
    - Terraform State: "pages/Terraform-state.md"
    - Trabajando con Terraform: "pages/working-with-terraform.md"
    - Terraform y AWS: "pages/TerraformAndAWS.md"
    - Remote State: "pages/remote-states.md"
    - Terraform provisioners: "pages/terraform-provisioners.md"
    - Import, Tainting Resources And Debugging: "pages/import-tainting-resources-debugging.md"
    - Functiones Y Condicionales: "pages/functions_and_conditionals.md"
  - Labortorios: "pages/labs/laboratios.md"
